autentication/urls.py
from django.urls import path
from .views import VRegistro

urlpatterns = [
    path('', VRegistro.as_view(), name="autentificacion"), 
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="blog"), 
    path('categoria/<int:categoria_id>', views.filtracategoria, name="categoria"),
]

carro/urls.py
from django.urls import path
from . import views

app_name= "carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregarProducto,  name="agregar"), 
    path('eliminar/<int:producto_id>/', views.eliminarProducto,  name="eliminar"), 
    path('restar/<int:producto_id>/', views.restarProducto,  name="restar"), 
    path('limpiar/', views.limpiarCarro,  name="limpiar"), 
]

contacto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contacto, name="contacto"), 
]

paginaWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('paginaWebapp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autentication.urls')),
]

paginaWebapp/urls.py
from django.urls import path
from paginaWebapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="home"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servicios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.servicios, name="servicios"), 
]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tienda, name="tienda"), 
]

autentication/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class categoria(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nombre

class post(models.Model):
    titulo=models.CharField(max_length=50)
    contenido=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to='blog', null = True, blank= True)
    autor=models.ForeignKey(User, on_delete=models.CASCADE)  # LLave foranea eliminacion en cascada
    categorias=models.ManyToManyField(categoria)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'post'
        verbose_name_plural = 'posts'
    
    def __str__(self):
        return self.titulo

servicios/models.py
from django.db import models

# Create your models here.

class servicio(models.Model):
    titulo=models.CharField(max_length=50)
    contenido=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to='servicios')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='servicio'
        verbose_name_plural='servicios'

    def __str__(self):        
        return self.titulo

tienda/models.py
from django.db import models

# Create your models here.
class categoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'categoriaProducto'
        verbose_name_plural = 'categoriasProductos'
    
    def __str__(self):
        return self.nombre

class Productos(models.Model):
    descripcion=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    imagen=models.ImageField(upload_to='productos', null = True, blank= True)
    categorias=models.ForeignKey(categoriaProd, on_delete=models.CASCADE) 
    precio=models.FloatField()
    existencia=models.IntegerField()
    disponible=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
    
    def __str__(self):
        return self.descripcion

contacto/forms.py
from django import forms

class formularioContacto(forms.Form):
    nombre=forms.CharField(label="Nombre", required=True)
    email=forms.EmailField(label="Correo", required=True)
    mensaje=forms.CharField(label="Comentario", required=True, widget=forms.Textarea)

autentication/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

class VRegistro(View):
    def get(self, request):
        form= UserCreationForm()
        return render(request, "registro/registro.html", {"form":form})
    def post(self, request):
        pass

blog/views.py
from django.shortcuts import render
from blog.models import post, categoria
# Create your views here.

def blog(request):
    listaBlogs = post.objects.all()   
    return render(request, "blog.html",  {"listaBlogs":listaBlogs, "valor":1})
    
def filtracategoria(request, categoria_id):
    lcategoria = categoria.objects.get(id=categoria_id)
    print(lcategoria.nombre)
    listaBlogs = post.objects.filter(categorias=lcategoria)
    #listaBlogs = post.objects.all()   
    print(listaBlogs)
    return render(request, "categorias.html", {"categorias":lcategoria, "listaBlogs":listaBlogs})

carro/views.py
from django.shortcuts import render

# Create your views here.

from .carro import Carro
from tienda.models import Productos
from django.shortcuts import redirect

def agregarProducto(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id=producto_id)
    carro.agregar(producto)
    return redirect("tienda")

def eliminarProducto(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id=producto_id)
    carro.eliminarProducto(producto)
    return redirect("tienda")

def restarProducto(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id=producto_id)
    carro.restar_producto(producto)
    return redirect("tienda")

def limpiarCarro(request, productoId):
    carro = Carro(request)
    producto = Productos.objects.get(id=productoId)
    carro.limparCarro()
    return redirect("tienda")
    

contacto/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from .forms import formularioContacto

# Create your views here.
def contacto(request):
    if request.method=="POST":
        miformulario = formularioContacto(request.POST)
        #miformulario.as_p()   ##Con parrafos
        #miformulario.as_ul()   ##Con forma de Lista
        #miformulario.as_table() #Con forma de Tabla 
        if miformulario.is_valid():
            ifform = miformulario.cleaned_data
            try:
                send_mail(ifform["nombre"] , ifform["mensaje"] ,ifform["email"],['agbsys@gmail.com'],fail_silently=False,)
                return redirect("/contacto/?valido")
            except:
                return redirect("/contacto/?novalido")

    else:
        miformulario = formularioContacto()
    return render(request, "contactos.html", {"form": miformulario})
    

paginaWebapp/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
def home(request):
    return render(request, "home.html", {"valor":request.path})

servicios/views.py
from django.shortcuts import render
from servicios.models import servicio

# Create your views here.

def servicios(request):
    listaServicios = servicio.objects.all()   
    return render(request, "servicios.html",  {"listaServicios":listaServicios, "valor":1})

tienda/views.py
from django.shortcuts import render
from .models import Productos, categoriaProd

# Create your views here.
def tienda(request):    
    listaProductos = Productos.objects.all()   
    return render(request, "tienda.html",  {"listaProductos":listaProductos, "valor":1})

autentication/templates/registro/registro.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<form method="post" action="" style="color:white; font:bold;">
    {% csrf_token %} 
    {{form}}
    <input type="submit" class="btn btn-primary"/>
</form>
{% endblock content %}

blog/templates/blog.html
{% extends "base.html" %}
{% load static %} 
{% block content %} 
{% for blog in listaBlogs %}
<section class="page-section clearfix">
<div class="container">
  <div class="intro">
    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{ blog.imagen.url }}" alt="" style="width: 50%;">
    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
      <h2 class="section-heading mb-4" >
        <span class="section-heading-lower">{{blog.titulo}}</span>
        <span class="section-heading-upper">{{blog.contenido}}</span>
      </h2>
      <div style="text-align: left;font-size: 0.8em;">Autor:{{blog.autor}}</div>
    </div>
  </div>
</div>
</section>
{% endfor %}
<section>
    <div style="width: 75%; margin: auto; text-align: center; color: white;">Categorias:
        {% for blog in listaBlogs %}
        {% for categoria in blog.categorias.all%}
        <a class="enlaceBlog" href="categoria\{{categoria.id}}" >{{categoria.nombre}}</a> &nbsp;
        {% endfor %}
        {% endfor %}
    </div>
</section>
{% endblock content %}

blog/templates/categorias.html
{% extends "base.html" %}
{% load static %} 
{% block content %} 
{% for blog in listaBlogs %}
<section class="page-section clearfix">
<div class="container">
  <div class="intro">
    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{ blog.imagen.url }}" alt="" style="width: 50%;">
    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
      <h2 class="section-heading mb-4" >
        <span class="section-heading-lower">{{blog.titulo}}</span>
        <span class="section-heading-upper">{{blog.contenido}}</span>
      </h2>
      <div style="text-align: left;font-size: 0.8em;">Autor:{{blog.autor}}</div>
    </div>
  </div>
</div>
</section>
{% endfor %}
<section>
    <div style="width: 75%; margin: auto; text-align: center; color: white;">Categorias:
        {% for blog in listaBlogs %}
        {% for categoria in blog.categorias.all%}
        {{categoria.nombre}} &nbsp;
        {% endfor %}
        {% endfor %}
    </div>
</section>
{% endblock content %}

contacto/templates/contactos.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
  

 <!-- Heading -->

    <div class="formulario">
      {% if "valido" in request.GET %}
        <p style="color: white;">Se envio su mensaje correctamente, Gracias</p>
      {% endif %}
      {% if "novalido" in request.GET %}
      <p style="color: red;">Ocurrio un Error al enviar su mensaje</p>
    {% endif %}
      {% if form.errors %}
        <p style="color: darkred;">Por favor revisa este campo</p>      
    {% endif %}
    <form action="" method="POST" style="text-align: center;">{% csrf_token %}
      <table style="color: white; margin: 20px auto;">{{form.as_table}}</table>
        <input type="submit" value="Enviar"  style="width: 150px;"/>
    </form>
    </div>

  {% endblock content %}

contacto/templates/error_envio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>ERROR: Servidor de Correo, no pudo enviar su correo</p>
</body>
</html>

contacto/templates/gracias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>!Gracias por contactarnos</p>
    <p>!Uno de nuestros asesores lo contactara</p>
</body>
</html>

paginaWebapp/templates/base.html
<html>

<head>

    {% load static %} 

    <!-- Bootstrap -->
    <link href="{% static 'paginaWebapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'paginaWebapp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h3 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Gestión de Pedidos</span>
      </h3>

      valor={{valor}}
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home' %}">Gestión de Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>      
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %} active {% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/servicios/' %} active {% endif %}  px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'servicios' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/tienda/' %} active {% endif %}  px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contacto/' %} active {% endif %}  px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'contacto' %}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path|slice:':6' == '/blog/' %} active {% endif %}  px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog' %}">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>

    <!-- Contenido Dinamico -->
    {% block content %}
   
    {% endblock content %}

    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'paginaWebapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'paginaWebapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

paginaWebapp/templates/home.html
  {% extends "base.html" %}
  {% load static %} 
  {% block content %}
    
  
   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'paginaWebapp/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>          
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock content %}

servicios/templates/servicios.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
  <h2><p style="color:white">Listado de Servicios</p></h2>
  {% for mser in listaServicios %}
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{ mser.imagen.url }}" alt="" style="width: 50%;">
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4" >
          <span class="section-heading-lower">{{mser.titulo}}</span>
          <span class="section-heading-upper">{{mser.contenido}}</span>
        </h2>
      </div>
    </div>
  </div>
</section>
  {% endfor %}
  {% endblock content %}

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr><th colspan="3" class="text-center">Carro de compras</th></tr>
        <tr><th>Producto</th><th>Cantidad</th><th>Precio</th></tr>
    </thead>
    <tbody>
        {% if request.session.carro.items  %}
          {% for key,value in request.session.carro.items %}
            <tr class="text-center"><td>{{value.descripcion}}</td><td>{{value.cantidad}}</td>
            <td><a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br>
            {{value.precio}}
            </td>
            </tr>
          {% endfor %}
          {% else %}
          <tr><th colspan="3" class="alert alert-danger text-center">Sin productos</th></tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr><td colspan="3"><p style="color: white;">Venta Total: $ {{ importe_total_carro }}</p> </td></tr>
    </tfoot>
</table>

tienda/templates/tienda.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<div class="conainer">
  <div style="float: left;">    
    {% include "carro/widget.html" %}
  </div>
<div class="row">
{% for producto in listaProductos %}
  <div class="col-md-3">
    <div class="card" style="width: 100%; margin-top: 5px;">
      <img  src="{{ producto.imagen.url }}" alt=""  class="card-img-top">
      <div class="card-body" style="text-align: center;">
      <h7 class="card-title">{{producto.descripcion}}</h7>
      <h7 class="card-body">{{producto.precio}}</h7>
      </div>
      <div class="card-footer text-center">
        <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar Producto</a>
      </div>
    </div>
  </div>
       
{% endfor %}
</div>
</div>
<section>
    <div style="width: 75%; margin: auto; text-align: center; color: white;">Categorias:
        {% for blog in listaBlogs %}
        {% for categoria in producto.categorias.all%}
        <a class="enlaceBlog" href="categoria\{{categoria.id}}" >{{categoria.nombre}}</a> &nbsp;
        {% endfor %}
        {% endfor %}
    </div>
</section>  
{% endblock content %}